apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redditbot.fullname" . }}
  labels:
    {{- include "redditbot.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "redditbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redditbot.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}