apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sniffingcat-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - '*.prepare.sh'
    secretName: wildcard-cert-tls-prod
  rules:
  - host: sniffingcat.env.prepare.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "redditbot.fullname" . }}
            port:
              number: {{ .Values.service.port }}