apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediabot-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - 'example.com'
    secretName: my-ssl-cert
  rules:
  - host: mediabot.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "redditbot.fullname" . }}
            port:
              number: {{ .Values.service.port }}